version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitProjectProdTest0609Project
  gitServerName: kusiProdVC
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
