version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitProjectProdTest0609Project
  gitServerName: kusiProdVC
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: kusiProdVC
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqagitprojectprodtest0609.integrations:testTpp
  packages:
  - name: SIQAGitProjectProdTest0609Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: services:add3Ints
  packages:
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
